# https://taskfile.dev
version: '3'

tasks:
  serve-main: UPSTREAM_HOST=localhost uv run fastapi dev server.py --port=8000
  serve-upstream: SIMULATE_FAILURE={{default "false" .CLI_ARGS}} uv run fastapi dev server.py --port=8001

  ruff: ruff check --fix --unsafe-fixes .
  pyright: pyright .

  hey: ./hey.sh {{.CLI_ARGS}}

  test-main: http GET localhost:8000/main?log_exception=true
  test-upstream: http GET localhost:8001/upstream
