# https://taskfile.dev
version: '3'

tasks:
  serve-main: uv run fastapi dev server.py --port=8000
  serve-upstream: SIMULATE_FAILURE={{default "false" .CLI_ARGS}} uv run fastapi dev server.py --port=8001

  ruff: uvx ruff check --fix --unsafe-fixes .
  pyright: uvx pyright .

  test-main: http GET localhost:8000/main?log_exception=true
  test-upstream: http GET localhost:8001/upstream
